name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening your first issue! 🎉 We appreciate your contribution to the DellServiceEntitlements PowerShell module. Please provide as much detail as possible to help us understand and address your concern."
        pr-message: "Welcome and thank you for your first pull request! 🚀 We're excited to see your contribution to the DellServiceEntitlements module. Please ensure your changes include appropriate tests and documentation updates where applicable."
